import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import chalk from 'chalk';
import prompts from 'prompts';
import { detectRepoRoot, detectRepoName, detectMainBranch, detectPackageManager, detectLanguage, detectScripts, validateTeamName, detectRemote } from './detect.js';
import { createLabels } from './labels.js';
import { createWorktrees, getTeamDir, discoverCoderCount } from './worktrees.js';
import { copyAgentProfiles, copyExtensionFiles, getPresetDir } from './copy.js';

/**
 * Check if a command-line tool is available.
 * @param {string} cmd - Command to check
 * @returns {boolean}
 */
function isAvailable(cmd) {
  try {
    execSync(`which ${cmd}`, {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Print the nightshift banner.
 */
function printBanner() {
  console.log('');
  console.log(chalk.bold('  nightshift'));
  console.log(chalk.dim('  Coordinating AI agents for your development pipeline'));
  console.log('');
}

/**
 * Parse a flag value from CLI arguments.
 * E.g., parseFlag(['--team', 'dev'], '--team') returns 'dev'.
 * @param {string[]} args - CLI arguments
 * @param {string} flag - Flag to look for (e.g., '--team')
 * @returns {string|null} Value after the flag, or null if not found
 */
function parseFlag(args, flag) {
  const idx = args.indexOf(flag);
  if (idx === -1 || idx + 1 >= args.length) {
    return null;
  }
  return args[idx + 1];
}

/**
 * List available preset names by scanning the presets directory.
 * @returns {string[]} Array of preset names
 */
function listAvailablePresets() {
  const presetsDir = join(getPresetDir(''), '..');
  if (!existsSync(presetsDir)) {
    return [];
  }
  return readdirSync(presetsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
}

/**
 * Generate repo.md content from detected project settings.
 * Auto-fills detected values, prompts for missing ones (unless skipPrompts is true).
 *
 * @param {string} packageManager - Detected package manager
 * @param {string} language - Detected language
 * @param {{ build: string|null, test: string|null, lint: string|null, typecheck: string|null }} scripts - Detected scripts
 * @param {string} mainBranch - Main branch name
 * @param {boolean} skipPrompts - If true, skip interactive prompts and use defaults
 * @returns {Promise<string>} Generated repo.md content
 */
export async function generateRepoMd(packageManager, language, scripts, mainBranch, skipPrompts) {
  const pm = packageManager || 'npm';

  // Build command strings from detected scripts
  let installCmd = `${pm} install`;
  let buildCmd = scripts.build ? `${pm} run build` : 'TODO';
  let typecheckCmd = scripts.typecheck ? `${pm} run typecheck` : 'TODO';
  let testCmd = scripts.test ? `${pm} run test` : 'TODO';
  let lintCmd = scripts.lint ? `${pm} run lint` : 'TODO';

  // Build verification command from available scripts
  const verifyParts = [];
  if (scripts.typecheck) verifyParts.push(`${pm} run typecheck`);
  if (scripts.lint) verifyParts.push(`${pm} run lint`);
  if (scripts.test) verifyParts.push(`${pm} run test`);
  let verifyCmd = verifyParts.length > 0 ? verifyParts.join(' && ') : 'TODO';

  if (!skipPrompts) {
    console.log('');
    console.log(chalk.bold('Configure repo.md (shared across all teams):'));
    console.log(chalk.dim('  Press Enter to accept detected values.'));
    console.log('');

    const response = await prompts([
      {
        type: 'text',
        name: 'installCmd',
        message: 'Install dependencies command',
        initial: installCmd,
      },
      {
        type: 'text',
        name: 'buildCmd',
        message: 'Build command',
        initial: buildCmd,
      },
      {
        type: 'text',
        name: 'typecheckCmd',
        message: 'Typecheck command',
        initial: typecheckCmd,
      },
      {
        type: 'text',
        name: 'testCmd',
        message: 'Test command',
        initial: testCmd,
      },
      {
        type: 'text',
        name: 'lintCmd',
        message: 'Lint command',
        initial: lintCmd,
      },
      {
        type: 'text',
        name: 'verifyCmd',
        message: 'Verification command (run before PRs)',
        initial: verifyCmd,
      },
    ]);

    installCmd = response.installCmd || installCmd;
    buildCmd = response.buildCmd || buildCmd;
    typecheckCmd = response.typecheckCmd || typecheckCmd;
    testCmd = response.testCmd || testCmd;
    lintCmd = response.lintCmd || lintCmd;
    verifyCmd = response.verifyCmd || verifyCmd;
  }

  return `# Repo Configuration

> This file contains repo-level settings shared across all nightshift teams.
> Generated by \`npx nightshift init\`. Customize for your project.

## Commands

| Action | Command |
|--------|---------|
| Install dependencies | \`${installCmd}\` |
| Build | \`${buildCmd}\` |
| Typecheck | \`${typecheckCmd}\` |
| Test | \`${testCmd}\` |
| Lint | \`${lintCmd}\` |

## Verification Command

Run this before creating PRs or reporting test results:

\`\`\`bash
${verifyCmd}
\`\`\`

## Branch Naming

Pattern: \`issue-{number}-{slug}\`

Example: \`issue-27-add-user-settings\`

The slug is 2-3 words from the issue title, kebab-case.

## Commit Messages

Pattern: \`{type}(issue-{number}): {description}\`

Where \`{type}\` is:
- \`feat\` — new feature
- \`fix\` — bug fix

## Tracker

| Setting | Value |
|---------|-------|
| Type | \`github\` |

## Runner

The command used to start Claude Code in each tmux pane (via \`npx nightshift start\`):

\`\`\`
claude --dangerously-skip-permissions
\`\`\`
`;
}

/**
 * Append or update the nightshift team section in CLAUDE.md.
 * - If CLAUDE.md doesn't exist: creates it with ## Nightshift Teams header + team subsection
 * - If CLAUDE.md exists but no ## Nightshift Teams: appends it
 * - If ## Nightshift Teams exists but no ### <team>: appends team subsection
 * - If ### <team> already exists: replaces it (regenerates)
 *
 * @param {string} repoRoot - Path to the repository root
 * @param {string} repoName - Name of the repository
 * @param {string} team - Team name
 * @param {number} coderCount - Number of coder agents
 */
export function appendClaudeMd(repoRoot, repoName, team, coderCount) {
  const claudeMdPath = join(repoRoot, 'CLAUDE.md');

  // Build the team subsection
  const teamSubsection = buildTeamSubsection(team, repoName, coderCount);

  if (!existsSync(claudeMdPath)) {
    // Create CLAUDE.md from scratch
    const content = `# ${repoName}\n\nProject documentation.\n\n## Nightshift Teams\n\n${teamSubsection}`;
    writeFileSync(claudeMdPath, content);
    return;
  }

  let content = readFileSync(claudeMdPath, 'utf-8');

  if (!content.includes('## Nightshift Teams')) {
    // Append the section
    content = content.trimEnd() + `\n\n## Nightshift Teams\n\n${teamSubsection}`;
    writeFileSync(claudeMdPath, content);
    return;
  }

  // ## Nightshift Teams exists — check for ### <team>
  const teamHeader = `### ${team}`;
  const teamHeaderIdx = content.indexOf(teamHeader);

  if (teamHeaderIdx === -1) {
    // Append the team subsection at the end of the Nightshift Teams section
    // Find the next ## heading after ## Nightshift Teams, or end of file
    const nightshiftIdx = content.indexOf('## Nightshift Teams');
    const afterNightshift = content.indexOf('\n## ', nightshiftIdx + 1);

    if (afterNightshift === -1) {
      // No next section — append at end
      content = content.trimEnd() + `\n\n${teamSubsection}`;
    } else {
      // Insert before the next ## section
      content = content.slice(0, afterNightshift).trimEnd() + `\n\n${teamSubsection}\n` + content.slice(afterNightshift);
    }
    writeFileSync(claudeMdPath, content);
    return;
  }

  // ### <team> exists — replace it
  // Find the end of this team subsection (next ### or ## or end of file)
  const afterTeamHeader = content.indexOf('\n', teamHeaderIdx);
  let endOfTeamSection = content.length;

  // Look for next ### or ## heading
  const nextH3 = content.indexOf('\n### ', afterTeamHeader + 1);
  const nextH2 = content.indexOf('\n## ', afterTeamHeader + 1);

  if (nextH3 !== -1 && (nextH2 === -1 || nextH3 < nextH2)) {
    endOfTeamSection = nextH3;
  } else if (nextH2 !== -1) {
    endOfTeamSection = nextH2;
  }

  content = content.slice(0, teamHeaderIdx) + teamSubsection + content.slice(endOfTeamSection);
  writeFileSync(claudeMdPath, content);
}

/**
 * Build the markdown subsection for a team.
 * @param {string} team - Team name
 * @param {string} repoName - Repository name
 * @param {number} coderCount - Number of coder agents
 * @returns {string} Markdown content
 */
function buildTeamSubsection(team, repoName, coderCount) {
  const teamDir = getTeamDir(repoName, team);

  let rows = '';
  rows += `| @ns-${team}-producer | Triage issues, create branches | _(runs from main)_ |\n`;
  rows += `| @ns-${team}-planner | Write implementation plans | \`${teamDir}/worktrees/planner/\` |\n`;
  rows += `| @ns-${team}-reviewer | Review plans and code | \`${teamDir}/worktrees/reviewer/\` |\n`;
  for (let i = 1; i <= coderCount; i++) {
    rows += `| @ns-${team}-coder-${i} | Implement from plans | \`${teamDir}/worktrees/coder-${i}/\` |\n`;
  }
  rows += `| @ns-${team}-tester | Run tests against PRs | \`${teamDir}/worktrees/tester/\` |\n`;

  return `### ${team}\n| Agent | Role | Worktree |\n|-------|------|----------|\n${rows}\nConfig: \`.claude/nightshift/ns-${team}-*.md\`\n`;
}

/**
 * Run the full nightshift init flow.
 * @param {string[]} args - CLI arguments
 */
export async function init(args) {
  // 1. Parse flags
  const team = parseFlag(args, '--team');
  const codersFlag = parseFlag(args, '--coders');
  const yes = args.includes('--yes');
  const reset = args.includes('--reset');
  const resetRepo = args.includes('--reset-repo');

  // 2. Validate --team required
  if (!team) {
    console.error(chalk.red('Please specify a team: npx nightshift init --team dev'));
    process.exit(1);
  }

  // 3. Validate team name
  if (!validateTeamName(team)) {
    console.error(chalk.red(`Invalid team name "${team}". Must start with a lowercase letter, contain only lowercase letters, digits, and hyphens, and end with a letter or digit.`));
    process.exit(1);
  }

  // 4. Validate preset exists
  const presetDir = getPresetDir(team);
  if (!existsSync(presetDir)) {
    const available = listAvailablePresets();
    console.error(chalk.red(`Unknown preset: ${team}. Available presets: ${available.join(', ')}`));
    process.exit(1);
  }

  // 5. Print banner
  printBanner();

  // 6. Check prerequisites
  console.log(chalk.bold('Checking prerequisites...'));

  const prerequisites = [
    { cmd: 'git', label: 'git', install: 'https://git-scm.com/downloads' },
    { cmd: 'gh', label: 'GitHub CLI (gh)', install: 'https://cli.github.com/' },
    { cmd: 'claude', label: 'Claude Code', install: 'https://docs.anthropic.com/claude-code' },
  ];

  let missingPrereqs = false;
  for (const prereq of prerequisites) {
    if (isAvailable(prereq.cmd)) {
      console.log(`  ${chalk.green('v')} ${prereq.label}`);
    } else {
      console.log(`  ${chalk.red('x')} ${prereq.label} — install: ${prereq.install}`);
      missingPrereqs = true;
    }
  }

  if (missingPrereqs) {
    console.log('');
    console.error(chalk.red('Missing prerequisites. Install them and try again.'));
    process.exit(1);
  }

  // 7. Validate repository
  console.log('');
  console.log(chalk.bold('Validating repository...'));
  let repoRoot;
  try {
    repoRoot = detectRepoRoot();
    console.log(`  ${chalk.green('v')} Git repository found`);
  } catch (err) {
    console.log(`  ${chalk.red('x')} ${err.message}`);
    process.exit(1);
  }

  try {
    detectRemote();
    console.log(`  ${chalk.green('v')} Remote origin configured`);
  } catch (err) {
    console.log(`  ${chalk.red('x')} ${err.message}`);
    process.exit(1);
  }

  // 8. Detect project
  console.log('');
  console.log(chalk.bold('Detecting project...'));
  const repoName = detectRepoName();
  const mainBranch = detectMainBranch();
  const packageManager = detectPackageManager(repoRoot);
  const language = detectLanguage(repoRoot);
  const scripts = detectScripts(repoRoot);
  console.log(`  ${chalk.green('v')} Repository: ${repoName}`);
  console.log(`  ${chalk.green('v')} Main branch: ${mainBranch}`);
  console.log(`  ${chalk.green('v')} Package manager: ${packageManager}`);
  console.log(`  ${chalk.green('v')} Language: ${language}`);

  // 9. Setup repo.md (only on first init or --reset-repo)
  console.log('');
  console.log(chalk.bold('Setting up repo.md...'));
  const repoMdPath = join(repoRoot, '.claude', 'nightshift', 'repo.md');
  if (!existsSync(repoMdPath) || resetRepo) {
    if (resetRepo && existsSync(repoMdPath) && !args.includes('--force')) {
      const confirm = await prompts({
        type: 'confirm',
        name: 'value',
        message: 'This will reset repo.md which affects all teams. Continue?',
        initial: false,
      });
      if (!confirm.value) {
        console.log(`  ${chalk.dim('  repo.md reset skipped')}`);
      } else {
        const content = await generateRepoMd(packageManager, language, scripts, mainBranch, yes);
        mkdirSync(join(repoRoot, '.claude', 'nightshift'), { recursive: true });
        writeFileSync(repoMdPath, content);
        console.log(`  ${chalk.green('v')} repo.md created`);
      }
    } else {
      const content = await generateRepoMd(packageManager, language, scripts, mainBranch, yes);
      mkdirSync(join(repoRoot, '.claude', 'nightshift'), { recursive: true });
      writeFileSync(repoMdPath, content);
      console.log(`  ${chalk.green('v')} repo.md created`);
    }
  } else {
    console.log(`  ${chalk.dim('  repo.md already exists (skipped)')}`);
  }

  // 10. Setup team config files
  console.log('');
  console.log(chalk.bold(`Setting up ${team} team...`));

  let coderCount = 1;
  if (codersFlag) {
    coderCount = parseInt(codersFlag, 10);
    if (isNaN(coderCount) || coderCount < 1 || coderCount > 4) {
      console.error(chalk.red('Invalid --coders value. Must be between 1 and 4.'));
      process.exit(1);
    }
  } else if (!yes) {
    const response = await prompts({
      type: 'number',
      name: 'count',
      message: 'Number of coder agents (1-4)',
      initial: 1,
      min: 1,
      max: 4,
    });
    coderCount = response.count || 1;
  }

  // 11. Copy team extension files (if not exist or --reset)
  console.log('');
  console.log(chalk.bold('Setting up team config...'));
  if (reset) {
    // Remove existing ns-<team>-*.md files before copying fresh
    const nightshiftExtDir = join(repoRoot, '.claude', 'nightshift');
    if (existsSync(nightshiftExtDir)) {
      const existingFiles = readdirSync(nightshiftExtDir).filter(
        (f) => f.startsWith(`ns-${team}-`) && f.endsWith('.md')
      );
      for (const file of existingFiles) {
        unlinkSync(join(nightshiftExtDir, file));
      }
    }
  }
  const { copied, skipped } = copyExtensionFiles(repoRoot, team);
  console.log(
    `  ${chalk.green('v')} ${copied.length} extension files created in .claude/nightshift/`
  );
  if (skipped.length > 0) {
    console.log(
      `  ${chalk.dim(`  ${skipped.length} files skipped (already exist)`)}`
    );
  }

  // 12. Create labels
  console.log('');
  console.log(chalk.bold('Creating GitHub labels...'));
  try {
    const labelsCreated = createLabels(team, presetDir);
    console.log(
      `  ${chalk.green('v')} ${labelsCreated} labels created`
    );
  } catch (err) {
    console.log(`  ${chalk.red('x')} Failed to create labels: ${err.message}`);
    console.log(
      `  ${chalk.dim('  Make sure you are authenticated with gh: gh auth login')}`
    );
    process.exit(1);
  }

  // 13. Build roles array for worktrees (excluding producer)
  const roles = [
    'planner',
    'reviewer',
    ...Array.from({ length: coderCount }, (_, i) => `coder-${i + 1}`),
    'tester',
  ];

  // 14. Create worktrees
  console.log('');
  console.log(chalk.bold('Creating agent worktrees...'));
  const teamDir = getTeamDir(repoName, team);
  try {
    createWorktrees(repoName, team, roles, mainBranch);
    console.log(`  ${chalk.green('v')} Worktrees created at ${teamDir}/worktrees/`);
  } catch (err) {
    console.log(`  ${chalk.red('x')} Failed to create worktrees: ${err.message}`);
    process.exit(1);
  }

  // 15. Install deps in worktrees
  console.log('');
  console.log(chalk.bold('Installing dependencies in worktrees...'));
  for (const role of roles) {
    const wtPath = join(teamDir, 'worktrees', role);
    try {
      execSync(`${packageManager} install`, {
        cwd: wtPath,
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe'],
        timeout: 120000,
      });
      console.log(`  ${chalk.green('v')} ${role}`);
    } catch {
      console.log(`  ${chalk.yellow('~')} ${role} — install may need manual run`);
    }
  }

  // 16. Copy agent profiles
  console.log('');
  console.log(chalk.bold('Installing agent profiles...'));
  try {
    const profilesCopied = copyAgentProfiles(team, coderCount);
    console.log(
      `  ${chalk.green('v')} ${profilesCopied.length} profiles installed to ~/.claude/agents/`
    );
  } catch (err) {
    console.log(`  ${chalk.red('x')} Failed to copy profiles: ${err.message}`);
    process.exit(1);
  }

  // 17. Update .gitignore with Claude Code runtime artifacts
  console.log('');
  console.log(chalk.bold('Updating .gitignore...'));
  try {
    const gitignorePath = join(repoRoot, '.gitignore');
    const marker = '# Claude Code runtime (added by nightshift)';
    const entries = `\n${marker}\n.claude/agent-memory/\n.claude/scheduled_tasks.lock\n`;
    let content = '';
    if (existsSync(gitignorePath)) {
      content = readFileSync(gitignorePath, 'utf-8');
    }
    if (!content.includes(marker)) {
      writeFileSync(gitignorePath, content.trimEnd() + '\n' + entries);
      console.log(`  ${chalk.green('v')} .gitignore updated`);
    } else {
      console.log(`  ${chalk.dim('  .gitignore already configured (skipped)')}`);
    }
  } catch (err) {
    console.log(`  ${chalk.yellow('~')} Failed to update .gitignore: ${err.message}`);
  }

  // 18. Update CLAUDE.md
  console.log('');
  console.log(chalk.bold('Updating CLAUDE.md...'));
  try {
    appendClaudeMd(repoRoot, repoName, team, coderCount);
    console.log(`  ${chalk.green('v')} Team section added to CLAUDE.md`);
  } catch (err) {
    console.log(`  ${chalk.red('x')} Failed to update CLAUDE.md: ${err.message}`);
  }

  // 18. Print next steps
  console.log('');
  console.log(chalk.green.bold('Done! nightshift is set up.'));
  console.log('');
  console.log(chalk.bold('Agents:'));
  console.log(`  @ns-${team}-producer`);
  console.log(`  @ns-${team}-planner`);
  console.log(`  @ns-${team}-reviewer`);
  for (let i = 1; i <= coderCount; i++) {
    console.log(`  @ns-${team}-coder-${i}`);
  }
  console.log(`  @ns-${team}-tester`);
  console.log('');
  console.log(chalk.bold('Next steps:'));
  console.log('');
  console.log('  1. Customize your team config:');
  console.log(`     ${chalk.dim('.claude/nightshift/repo.md')}      — commands and settings (shared)`);
  console.log(`     ${chalk.dim(`.claude/nightshift/ns-${team}-*.md`)} — team-specific config`);
  console.log('');
  console.log('  2. Commit the pipeline files:');
  console.log(`     ${chalk.cyan(`git add .gitignore .claude/nightshift/ CLAUDE.md && git commit -m "chore: set up nightshift ${team} team"`)}`);
  console.log('');
  console.log('  3. Start the agents:');
  console.log(`     ${chalk.cyan(`npx nightshift start --team ${team}`)}`);
  console.log('');
  console.log(chalk.dim('     Or start individually in separate terminals:'));
  console.log(`     ${chalk.dim(`/loop 15m @ns-${team}-producer`)}`);
  console.log(`     ${chalk.dim(`/loop 15m @ns-${team}-planner`)}`);
  console.log(`     ${chalk.dim(`/loop 15m @ns-${team}-reviewer`)}`);
  for (let i = 1; i <= coderCount; i++) {
    console.log(`     ${chalk.dim(`/loop 15m @ns-${team}-coder-${i}`)}`);
  }
  console.log(`     ${chalk.dim(`/loop 15m @ns-${team}-tester`)}`);
  console.log('');
}
